services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    privileged: true
    ports:
      - "6052:6052"
    volumes:
      - ./docker/esphome/esp-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
