version: '3.8'
services:
  lora-reader:
    image: python:3.11
    container_name: lora-reader
    volumes:
      - ./app:/app
    working_dir: /app
    command: python reader.py
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
  webserver:
    image: python:3.11
    container_name: lora-webserver
    volumes:
      - ./app:/app
    working_dir: /app
    command: python webserver.py
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - lora-reader
