esphome:
  name: lora-receiver
  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            pinMode(36, OUTPUT);
            digitalWrite(36, LOW);
            delay(100);
  includes:
    - my_components/web_lora_component/web_lora_component.h

  external_components:
    - source:
        type: local
        path: /config/my_components

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  level: VERBOSE

## OTA (Over-the-Air) update support
ota:
  platform: esphome
  password: !secret ota_password


wifi:
  ap:
    ssid: "meshtastic-node"
    password: "meshpassword"

i2c:
  - id: bus_a
    sda: 17
    scl: 18

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 21
    i2c_id: bus_a
    address: 0x3C
    lambda: |-
      snprintf(mac, sizeof(mac), "%02X:%02X:%02X:%02X:%02X:%02X", 
        (uint8_t)(ESP.getEfuseMac() >> 40),
        (uint8_t)(ESP.getEfuseMac() >> 32),
        (uint8_t)(ESP.getEfuseMac() >> 24),
        (uint8_t)(ESP.getEfuseMac() >> 16),
        (uint8_t)(ESP.getEfuseMac() >> 8),
        (uint8_t)(ESP.getEfuseMac()));
      it.print(4, 4, id(roboto_20), "Hello World node 3! " + mac);

font:
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20

interval:
  - interval: 60s
    then:
      - lambda: |-
          char mac[18];
          snprintf(mac, sizeof(mac), "%02X:%02X:%02X:%02X:%02X:%02X", 
            (uint8_t)(ESP.getEfuseMac() >> 40),
            (uint8_t)(ESP.getEfuseMac() >> 32),
            (uint8_t)(ESP.getEfuseMac() >> 24),
            (uint8_t)(ESP.getEfuseMac() >> 16),
            (uint8_t)(ESP.getEfuseMac() >> 8),
            (uint8_t)(ESP.getEfuseMac()));
          ESP_LOGI("lora", "Sending MAC via LoRa: %s", mac);
          global_web_lora_component->send_number((int32_t)ESP.getEfuseMac());
