esphome:
  name: lora-gateway
  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            pinMode(36, OUTPUT);
            digitalWrite(36, LOW);
            delay(100);
  includes:
    - my_components/web_lora_component/web_lora_component.h

external_components:
  - source:
      type: local
      path: /config/my_components

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  level: VERBOSE


globals:
  - id: last_lora_message
    type: std::string
    restore_value: no
    initial_value: '""'

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 21
    i2c_id: bus_a
    address: 0x3C
    lambda: |-
      it.print(4, 4, id(roboto_20), "LoRa RX: ");
      it.print(4, 28, id(roboto_20), id(last_lora_message).c_str());

interval:
  - interval: 1s
    then:
      - lambda: |-
          if (LoRa.parsePacket()) {
            String msg = "";
            while (LoRa.available()) {
              msg += (char)LoRa.read();
            }
            id(last_lora_message) = msg.c_str();
            ESP_LOGI("lora", "Received LoRa: %s", msg.c_str());
          }
wifi:
  ap:
    ssid: "meshtastic-node"
    password: "meshpassword"

i2c:
  - id: bus_a
    sda: 17
    scl: 18

font:
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20


