esphome:
  name: heltechelloworld-0
  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            pinMode(36, OUTPUT);
            digitalWrite(36, LOW);
            delay(100);
  libraries:
    - "SPI"
    - "Ticker"
    - "SX126x-Arduino"
    - "ArduinoJson"
    - "CayenneLPP"

external_components:
  - source:
      type: local
      path: components 
    components: ["lora_sx126x"]

esp32:
  board: heltec_wifi_lora_32_V3
  framework:
    type: arduino

# Enable logging
logger:
  hardware_uart: "UART0"  # Heltec V3 boards
  level: DEBUG
  
# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Static IP configuration (optional)
#  manual_ip:
#    static_ip: 192.168.1.100
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case WiFi connection fails
 # ap:
 #   ssid: "Heltec Hello World"
 #   password: "hello"

#captive_portal:

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

time:
  - platform: homeassistant
    id: esptime

# I2C configuration for the OLED display
spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
  miso_pin: GPIO11

i2c:
  - id: bus_a
    sda: 17
    scl: 18
    scan: true

# SSD1306 OLED display configuration
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 21
    i2c_id: bus_a
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(roboto_16), "Hello World 0!");
      it.strftime(64, 32, id(roboto_16), TextAlign::CENTER, "%H:%M", id(esptime).now());

## Fonts for OLED display
font:
  - file: "gfonts://Nova+Mono"
    id: roboto_16
    size: 16
  - file: "gfonts://Roboto"
    id: roboto_10
    size: 10

lora_sx126x:
  rf_frequency: 868000000          # Manditory for user to set

sensor:
  - platform: lora_sx126x
    id: lorarssi
    name: lorarssi                 # Required for publishing into API and HA 

#  - platform: lora_sx126x
#    id: lorarssi
#    name: lorarssi                 # Required for publishing into API and HA 

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
  - platform: version
    name: "ESPHome Version"
  - platform: template
    name: "Template Text Sensor"
    lambda: |-
      return {"Hello World 0"};
    update_interval: 60s
  - platform: lora_sx126x
    id: packet_in
    name: packet_in
  
binary_sensor:
  - platform: gpio
    pin: 5
    id: trigger
    name: "Trigger (In)"
    on_press:
      then:
        - switch.turn_on: monitor_switch    
    on_release:
      then:
        - switch.turn_off: monitor_switch

output:
  - platform: gpio
    pin: 6
    id: monitor
  - platform: gpio
    pin: 35
    id: monitor_led
    
switch:
  - platform: output
    id: monitor_switch
    name: "Monitor Output (Out)"
    output:
#     monitor
      monitor_led

button:
  - platform: restart
    name: "Restart"

  