esphome:
  name: heltechelloworld_0
  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            pinMode(36, OUTPUT);
            digitalWrite(36, LOW);
            delay(100);
  includes:
    - components/my_lorawan_component.h
    - components/lorawan_secrets.h
  libraries:
    - "SPI"
    - "Ticker"
    - "SX126x-Arduino"
    - "ArduinoJson"
    - "CayenneLPP"

external_components:
  - source:
      type: local
      path: components 
    components: ["lorawan_sx126x"]

esp32:
  board: heltec_wifi_lora_32_V3
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  
# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Static IP configuration (optional)
#  manual_ip:
#    static_ip: 192.168.1.100
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case WiFi connection fails
 # ap:
 #   ssid: "Heltec Hello World"
 #   password: "hello"

#captive_portal:

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

time:
  - platform: homeassistant
    id: esptime

# I2C configuration for the OLED display
spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
  miso_pin: GPIO11

i2c:
  - id: bus_a
    sda: 17
    scl: 18
    scan: true

# SSD1306 OLED display configuration
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 21
    i2c_id: bus_a
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(roboto_16), "Hello World 0!");
      it.strftime(64, 32, id(roboto_16), TextAlign::CENTER, "%H:%M", id(esptime).now());

## Fonts for OLED display
font:
  - file: "gfonts://Nova+Mono"
    id: roboto_16
    size: 16
  - file: "gfonts://Roboto"
    id: roboto_10
    size: 10

# LoRaWAN Specific Oprions
# Setting these will enable the LoRaWAN radio mode
lorawan_sx126x:

# # Interface to radio chip
# pin_lora_reset: 12  # LoRa Reset
# pin-lora_dio_1: 14  # LoRa DIO_1
# pin_lora_busy:  13  # LoRa SPI Busy
# pin_lora_nss:    8  # LoRa SPI CS (Chip Select)
# pin_lora_sclk:   9  # LoRa SPI SCLK
# pin_lora_miso:  11  # LoRa SPI MISO (Master In, Slave Out)
# pin_lora_mosi:  10  # LoRa SPI MOSI (Master Out, Slave In)
# radio_txen:     -1  # LoRa Antenna TX Enable, on some boards.
# radio_rxen:     -1  # LoRa Antenna RX Enable, on some boards.

  region: AU915
#     # AS923
#     # AU915
#     # CN470
#     # CN779
#     # EU433
#     # EU868
#     # IN865
#     # KR920
#     # US915
#     # AS923_2
#     # AS923_3
#     # AS923_4
#     # RU864
  subchannel: 2
  device_type: CLASS_A
#     # CLASS_B
#     # CLASS_C

  authentication: OTAA
    # OTAA - Over the Air
    # ABP - Activation by Personalization

# device_eui: !secret lorawan_device_eui   # 8 bytes
    # The Device EUI is unique to the device, It can be set here, or will be set
    # using the WiFi MAC address, If it is set automatically, then this code
    # won't need to be recompiled for every device.
    
  app_eui: !secret lorawan_join_eui    # 8 bytes     
    # Also referred to as 'join_eui'

    # The following is used for Over The Air Authentication (OTAA)
  app_key:  !secret lorawan_app_key   # 16 bytes

#   # The following is required for Activation By Personalization (ABP) - Untested
#   nwks_key: "00000000000000000000000000000000"  # 16 bytes
#   apps_key: "00000000000000000000000000000000"  # 16 bytes
#   dev_addr: "00000000000000000000000000000000"  # 16 bytes