esphome:
  name: heltechelloworld_2
  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            pinMode(36, OUTPUT);
            digitalWrite(36, LOW);
            delay(100);
  includes:
    - components/my_lorawan_component.h
    - components/lorawan_secrets.h
  libraries:
    - "SPI"
    - "Ticker"
    - "SX126x-Arduino"
    - "ArduinoJson"
    - "CayenneLPP"

esp32:
  board: heltec_wifi_lora_32_V3
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  
# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Static IP configuration (optional)
#  manual_ip:
#    static_ip: 192.168.1.100
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case WiFi connection fails
 # ap:
 #   ssid: "Heltec Hello World"
 #   password: "hello"

#captive_portal:

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

time:
  - platform: homeassistant
    id: esptime

# I2C configuration for the OLED display
spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
  miso_pin: GPIO11

i2c:
  - id: bus_a
    sda: 17
    scl: 18
    scan: true

# SSD1306 OLED display configuration
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 21
    i2c_id: bus_a
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(roboto_16), "Hello World 2!");
      it.strftime(64, 32, id(roboto_16), TextAlign::CENTER, "%H:%M", id(esptime).now());

## Fonts for OLED display
font:
  - file: "gfonts://Nova+Mono"
    id: roboto_16
    size: 16
  - file: "gfonts://Roboto"
    id: roboto_10
    size: 10

sx1262_lorawan:
  id: lorawan_1
  device_eui: "{0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}"
  app_eui:    "{0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}"
  app_key:    "{0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}"
