esphome:
  name: heltec-node-1
  libraries:
    - "SPI"
    - "WIFI"
    - "Ticker"
    - "SX126x-Arduino"
    - "https://github.com/sandeepmistry/arduino-LoRa.git"

external_components:
  - source:
      type: local
      path: /config/components

esp32:
  board: heltec_wifi_lora_32_V3
  framework:
    type: arduino

logger:

  
## WiFi configuration (Access Point only)
wifi:
  ap:
    ssid: "meshtastic-node"
    password: "meshpassword"
  # No fallback, no scanning for networks

spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
  miso_pin: GPIO11

i2c:
  - id: bus_a
    sda: 17
    scl: 18

text_sensor:
  - id: received_msg
    name: "Received Message"
    icon: "mdi:message-text"


## Fonts for OLED display
font:
# gfonts://family[@weight]
#  - file: "gfonts://Roboto+Mono"
  - file: "gfonts://Nova+Mono"
    id: roboto_16
    size: 16
  - file: "gfonts://Roboto"
    id: roboto_10
    size: 10

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 21
    i2c_id: bus_a
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(roboto_10), "Node 1");
      it.printf(0, 20, id(roboto_10), "Ontvangen:");
      it.printf(0, 40, id(roboto_10), "%s", id(received_msg).c_str());

heltec_wifi_lora:
  name: "Node 1"
  received_msg_sensor: received_msg